version: '2'

services:
  datastore:
    image: busybox
    volumes:
      # put your drupal source code and mount as volume.
      - ./volumes/drupal:/var/www/html
    container_name: drupal_datastore
  mysql:
    image: mariadb:10.1
    volumes:
      # override mysql config if necessary.
      - ./mysql/server.cnf:/etc/mysql/conf.d/server.cnf
      # It is also possible to save mysql files to on host filesystem.
      # - ./volumes/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    ports:
      - "3306:3306"
    container_name: drupal_mysql
  php:
    image: blauerberg/drupal-php:7.0-fpm
    volumes_from:
      - datastore
    volumes:
      # allocate large memory_limit for drush.
      - ./php/php.ini:/usr/local/etc/php/php.ini
      # override php-fpm config to use xdebug with port 9000.
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
    links:
      - mysql
    container_name: drupal_php
  nginx:
    image: nginx:1.10
    volumes_from:
      - datastore
    links:
      - php
    volumes:
      # override nginx config to execute drupal through the php container.
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    container_name: drupal_nginx
