version: '3.8'

services:
  db:
    image: mariadb:10.2
    #image: mysql:5.7

  php:
    image: blauerberg/drupal-php:7.1-fpm
    #image: blauerberg/drupal-php:7.0-fpm
    #image: blauerberg/drupal-php:5.6-fpm
    #image: blauerberg/drupal-php:7.1-apache
    #image: blauerberg/drupal-php:7.0-apache
    #image: blauerberg/drupal-php:5.6-apache
    links:
      - db

  web:
    image: nginx:latest
    links:
      - php

