# This file will be load at executing "docker-compose up".
# The setting is for the development environment.
# @see https://docs.docker.com/compose/extends/

version: '3'

services:
  db:
    volumes:
      # override mysql config if necessary.
      - ./mysql/server.cnf:/etc/mysql/conf.d/server.cnf
      # It is also possible to save mysql files to on host filesystem.
      # - ./volumes/mysql:/var/lib/mysql
      # If /docker-entrypoint-initdb.d/*.sql.gz is exists at generating the container,
      # it will be loaded by mariadb and will restore only once.
      # - ./initdb.sql.gz:/docker-entrypoint-initdb.d/initdb.sql.gz
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    ports:
      - "3306:3306"

  php:
    build: php/php-fpm
    volumes:
      # put your drupal source code and mount as volume.
      - ./volumes/drupal:/var/www/html:cached
      # Replace volume to this to use docker-sync for mac OS users to resolve performance issue.
      # See also: https://github.com/docker/for-mac/issues/77
      # - drupal_source:/var/www/html:rw
      # allocate large memory_limit for drush.
      - ./php/php/php.ini:/usr/local/etc/php/php.ini
      # override php-fpm config to use xdebug with port 9000.
      - ./php/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php/php-fpm/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      # override sendmail_path to use mailhog
      - ./php/php-fpm/sendmail_path.conf:/usr/local/etc/php-fpm.d/sendmail_path.conf
      - ./php/ssmtp/ssmtp.conf:/etc/ssmtp/ssmtp.conf
      # use your host's ssh key, drushrc
      # - ~/.ssh/id_rsa:/root/.ssh/id_rsa:ro
      # - ~/.drush/aliases.drushrc.php:/root/.drush/aliases.drushrc.php:ro

  # for apache image
  #php:
  #  volumes:
  #    # put your drupal source code and mount as volume.
  #    - ./volumes/drupal:/var/www/html:cached
  #    # Replace volume to this to use docker-sync for mac OS users to resolve performance issue.
  #    # See also: https://github.com/docker/for-mac/issues/77
  #    # - drupal_source:/var/www/html:rw
  #    - ./apache2/php/php.ini:/usr/local/etc/php/php.ini
  #    - ./apache2/ssmtp/ssmtp.conf:/etc/ssmtp/ssmtp.conf
  #    - ./apache2/apache2/default.conf:/etc/apache2/sites-available/000-default.conf
  #    #- ./apache2/apache2/default_for_drupal_composer.conf:/etc/apache2/sites-available/000-default.conf
  #    # use your host's ssh key, drushrc
  #    #- ~/.ssh/id_rsa:/root/.ssh/id_rsa:ro
  #    #- ~/.drush/aliases.drushrc.php:/root/.drush/aliases.drushrc.php:ro
  #    #- ~/.drush/drushrc.php:/root/.drush/drushrc.php:ro
  #  ports:
  #    - "80:80"

  web:
    environment:
      VIRTUAL_HOST: localhost
    volumes:
      # put your drupal source code and mount as volume.
      - ./volumes/drupal:/var/www/html:cached
      # Replace volume to this to use docker-sync for mac OS users to resolve performance issue.
      # See also: https://github.com/docker/for-mac/issues/77
      # - drupal_source:/var/www/html:rw
      # override nginx config to execute drupal through the php container.
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      #- ./nginx/default_for_drupal_composer.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/override_for_development.conf:/etc/nginx/conf.d/override_for_development.conf

  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx-proxy/override_for_development.conf:/etc/nginx/conf.d/override_for_development.conf
    ports:
      - "80:80"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_PORT: 3306
    links:
      - db
    volumes:
      - ./phpmyadmin/php-fpm.conf:/etc/php-fpm.conf
    ports:
       - 8080:80

#volumes:
#  drupal_source:
#    external: true
